apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 20
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: echo-server
          image: hashicorp/http-echo
          args:
            - -text="Hello world!"
            - -listen=:8080
          ports:
            - name: http-port
              containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 100Mi
            requests:
              cpu: 250m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: http-server
